[package]
name = "atomic-plugin-example"
version = "0.1.0"
authors = ["Joep Meindertsma <joep@ontola.io>"]
edition = "2018"

[lib]
name = "atomic_plugin_example"
crate-type = ["cdylib"]

# Make wasm size smaller: https://rustwasm.github.io/docs/book/reference/code-size.html#optimizing-builds-for-code-size
[profile.release]
lto = true
